model:
  params:
    adapter_config:
      name: sketch
      target: Adapter.models.adapters.Adapter_XL
      params:
        cin: 256
        channels: [320, 640, 1280, 1280]
        nums_rb: 2
        ksize: 1
        sk: true
        use_conv: false
      pretrained: /mnt/nfs/file_server/public/mingjiahui/models/T2IAdapter/adapter-xl-sketch.pth  # checkpoints/adapter-xl-sketch.pth